export const THREAT_ROWS_SECONDARY = [
  [
    "G14",
    "P0",
    "clean-home test mutates inherited real profile",
    "hostile environment manifest",
    "resolved roots contained and real manifests unchanged",
    "E-PKG",
    ["A-PKG"],
    900000,
    "real profile mutation",
    ".omo/evidence/release/{runId}/G14.json",
  ],
  [
    "G15",
    "P0",
    "doctor green hides broken extension import",
    "broken import fixture",
    "public loader reports failure and good load registers",
    "E-PKG",
    ["A-PKG", "A-LIFE"],
    300000,
    "doctor substituted for load",
    ".omo/evidence/release/{runId}/G15.json",
  ],
  [
    "G16",
    "P0",
    "link or tarball path is mislabeled npm proof",
    "exact tarball bytes",
    "lstat link and ordinary staged directory are distinct",
    "E-PKG",
    ["A-PKG"],
    900000,
    "false npm claim",
    ".omo/evidence/release/{runId}/G16.json",
  ],
  [
    "G17",
    "P0",
    "post-publish smoke is claimed as prior gate",
    "candidate tarball digest",
    "prepublication verdict precedes deferred public audit",
    "E-PKG",
    ["A-REL"],
    1200000,
    "registry promotion",
    ".omo/evidence/attestor-{runId}/G17.json",
  ],
  [
    "G18",
    "P0",
    "workflow assumes direct native Goal state",
    "Goal-disabled runtime fixture",
    "complete lifecycle uses plugin snapshot authority",
    "E-WORKFLOW",
    ["A-LIFE"],
    600000,
    "native Goal mutation",
    ".omo/evidence/replay/{runId}/G18.json",
  ],
  [
    "G19",
    "P1",
    "command alias collision silently misroutes",
    "hostile extension order",
    "registry ownership and collision diagnosis",
    "E-ACT",
    ["A-LIFE"],
    300000,
    "silent alias takeover",
    ".omo/evidence/replay/{runId}/G19.json",
  ],
  [
    "G20",
    "P1",
    "multiple stop handlers make continuation nondeterministic",
    "handler inventory",
    "one coordinator and documented coexistence ordering",
    "E-STATE",
    ["A-LIFE", "A-STATE"],
    300000,
    "duplicate continuation",
    ".omo/evidence/replay/{runId}/G20.json",
  ],
  [
    "G21",
    "P1",
    "async-disabled fallback claims concurrent team",
    "disabled job manager fixture",
    "explicit blocker with no roster success state",
    "E-TEAM",
    ["A-LIFE"],
    300000,
    "false team launch",
    ".omo/evidence/replay/{runId}/G21.json",
  ],
  [
    "G22",
    "P1",
    "mutable plan hash rejects progress or trusts replacement",
    "plan edit corpus",
    "checkbox edit accepted and task replacement blocked",
    "E-STATE",
    ["A-STATE"],
    120000,
    "unreconciled replacement",
    ".omo/evidence/replay/{runId}/G22.json",
  ],
  [
    "G23",
    "P1",
    "in-memory cap is claimed durable on restart",
    "restart schedule",
    "outer and persisted counters have separate oracles",
    "E-STATE",
    ["A-LIFE", "A-STATE"],
    300000,
    "false durable bound",
    ".omo/evidence/replay/{runId}/G23.json",
  ],
  [
    "G24",
    "P1",
    "cleanup or lcx mutates unowned resources",
    "foreign sentinel tree",
    "refusal and dry-run preserve external sentinels",
    "E-WORKFLOW",
    ["A-SEC"],
    600000,
    "unowned side effect",
    ".omo/evidence/replay/{runId}/G24.json",
  ],
  [
    "G25",
    "P1",
    "package provenance is ambiguous or mutable",
    "lockfile and source records",
    "recomputed versions commit and tarball hashes",
    "E-PKG",
    ["A-PKG", "A-REL"],
    900000,
    "mutable provenance",
    ".omo/evidence/release/{runId}/G25.json",
  ],
  [
    "G26",
    "P0",
    "trigger token in untrusted file content or tool output activates a directive",
    "injected file and tool output corpus",
    "activation counter remains zero after untrusted content processing",
    "E-ACT",
    ["A-SEC"],
    120000,
    "untrusted directive activation",
    ".omo/evidence/replay/{runId}/G26.json",
  ],
  [
    "G27",
    "P0",
    "continuation budget exhaustion emits a further continuation",
    "saturated counter fixture",
    "post-saturation idle produces no continuation and records reason",
    "E-STATE",
    ["A-LIFE", "A-STATE"],
    300000,
    "post-saturation continuation",
    ".omo/evidence/replay/{runId}/G27.json",
  ],
  [
    "G28",
    "P0",
    "rules-injection budget starvation emits a partial rule or locationless catalog entry",
    "oversized rule corpus",
    "output contains only whole units with locations and respects byte budget",
    "E-ACT",
    ["A-SEC", "A-LIFE"],
    120000,
    "partial rule emission",
    ".omo/evidence/replay/{runId}/G28.json",
  ],
  [
    "G29",
    "P0",
    "forged or replayed model-chain provenance record is accepted",
    "tampered provenance fixture",
    "provenance validation refuses forged records and logs rejection",
    "E-ARCH",
    ["A-SEC", "A-STATE"],
    120000,
    "forged provenance acceptance",
    ".omo/evidence/replay/{runId}/G29.json",
  ],
] as const
