import { z } from "zod"

const principalSchema = z.enum(["E-ARCH", "E-STATE", "E-ACT", "E-TEAM", "E-WORKFLOW", "E-PKG"])
const attestorSchema = z.enum(["A-STATE", "A-LIFE", "A-SEC", "A-PKG", "A-REL"])
const scenarioSchema = z
  .object({
    id: z.string().regex(/^G(?:0[1-9]|1[0-9]|2[0-5])$/),
    priority: z.enum(["P0", "P1"]),
    risk: z.string().min(10),
    immutableInput: z.string().min(3),
    oracle: z.string().min(10),
    executor: principalSchema,
    attestors: z.array(attestorSchema).min(1).readonly(),
    timeoutMs: z.number().int().positive(),
    forbiddenSideEffects: z.array(z.string().min(3)).min(1).readonly(),
    evidencePath: z.string().regex(/^\.omo\/evidence\/[A-Za-z0-9{}/._-]+$/),
  })
  .strict()

// SIZE_OK: G01-G25 is a single reviewable pure-data registry; splitting it would hide omissions.
const rows = [
  [
    "G01",
    "P0",
    "executor fabricates self-consistent green evidence",
    "commit and tarball hashes",
    "verifier-launched OS exits and raw streams",
    "E-ARCH",
    ["A-REL"],
    1200000,
    "executor release verdict",
    ".omo/evidence/attestor-{runId}/G01.json",
  ],
  [
    "G02",
    "P0",
    "malformed state resets bounds or escapes root",
    "fixture bytes and commit",
    "pre/post hashes and unchanged external sentinels",
    "E-STATE",
    ["A-STATE", "A-SEC"],
    120000,
    "state mutation",
    ".omo/evidence/replay/{runId}/G02.json",
  ],
  [
    "G03",
    "P0",
    "repeated turn zero suppresses natural stops",
    "two durable leaf ids",
    "distinct leaves continue and replay is idempotent",
    "E-STATE",
    ["A-LIFE"],
    300000,
    "duplicate continuation",
    ".omo/evidence/replay/{runId}/G03.json",
  ],
  [
    "G04",
    "P0",
    "timed-out handler performs a late side effect",
    "delay point and state hash",
    "wait beyond deadline then compare all sentinels",
    "E-STATE",
    ["A-STATE", "A-LIFE"],
    900000,
    "late state or message write",
    ".omo/evidence/replay/{runId}/G04.json",
  ],
  [
    "G05",
    "P0",
    "prompt injection mutates state or exfiltrates",
    "injection corpus",
    "tool denial receipts and unchanged revision",
    "E-ACT",
    ["A-SEC"],
    120000,
    "forbidden tool call",
    ".omo/evidence/replay/{runId}/G05.json",
  ],
  [
    "G06",
    "P0",
    "synthetic prompt recursively activates workflow",
    "scripted provider transcript",
    "activation counter and revision remain one",
    "E-ACT",
    ["A-LIFE"],
    300000,
    "recursive activation",
    ".omo/evidence/replay/{runId}/G06.json",
  ],
  [
    "G07",
    "P0",
    "flat or batch task shape bypasses fanout cap",
    "task shape corpus",
    "dispatcher receipts and durable item count",
    "E-TEAM",
    ["A-SEC", "A-LIFE"],
    300000,
    "excess task launch",
    ".omo/evidence/replay/{runId}/G07.json",
  ],
  [
    "G08",
    "P0",
    "requested name is mistaken for actual agent id",
    "native task result bytes",
    "stored and messaged IDs equal returned runtime IDs",
    "E-TEAM",
    ["A-LIFE"],
    300000,
    "wrong peer message",
    ".omo/evidence/replay/{runId}/G08.json",
  ],
  [
    "G09",
    "P0",
    "unowned cancellation is reported successful",
    "owned and foreign job ids",
    "job status and owner receipts remain accurate",
    "E-TEAM",
    ["A-LIFE"],
    300000,
    "foreign job cancellation",
    ".omo/evidence/replay/{runId}/G09.json",
  ],
  [
    "G10",
    "P0",
    "worker settles with invalid evidence artifact",
    "artifact fixture tree",
    "realpath regular nonempty current artifact check",
    "E-TEAM",
    ["A-SEC"],
    120000,
    "accept invalid receipt",
    ".omo/evidence/replay/{runId}/G10.json",
  ],
  [
    "G11",
    "P0",
    "active lookup selects foreign or duplicate run",
    "active index fixture",
    "typed conflict and unchanged state bytes",
    "E-STATE",
    ["A-STATE"],
    120000,
    "wrong-run commit",
    ".omo/evidence/replay/{runId}/G11.json",
  ],
  [
    "G12",
    "P0",
    "lock age stealing lets stale owner commit",
    "two process schedule",
    "contention has no write and explicit repair audit",
    "E-STATE",
    ["A-STATE"],
    900000,
    "automatic lock steal",
    ".omo/evidence/replay/{runId}/G12.json",
  ],
  [
    "G13",
    "P0",
    "abort is mislabeled paused cancelled or complete",
    "slow stop transcript",
    "active state persists without explicit control command",
    "E-WORKFLOW",
    ["A-LIFE", "A-STATE"],
    300000,
    "workflow status mutation",
    ".omo/evidence/replay/{runId}/G13.json",
  ],
  [
    "G14",
    "P0",
    "clean-home test mutates inherited real profile",
    "hostile environment manifest",
    "resolved roots contained and real manifests unchanged",
    "E-PKG",
    ["A-PKG"],
    900000,
    "real profile mutation",
    ".omo/evidence/release/{runId}/G14.json",
  ],
  [
    "G15",
    "P0",
    "doctor green hides broken extension import",
    "broken import fixture",
    "public loader reports failure and good load registers",
    "E-PKG",
    ["A-PKG", "A-LIFE"],
    300000,
    "doctor substituted for load",
    ".omo/evidence/release/{runId}/G15.json",
  ],
  [
    "G16",
    "P0",
    "link or tarball path is mislabeled npm proof",
    "exact tarball bytes",
    "lstat link and ordinary staged directory are distinct",
    "E-PKG",
    ["A-PKG"],
    900000,
    "false npm claim",
    ".omo/evidence/release/{runId}/G16.json",
  ],
  [
    "G17",
    "P0",
    "post-publish smoke is claimed as prior gate",
    "candidate tarball digest",
    "prepublication verdict precedes deferred public audit",
    "E-PKG",
    ["A-REL"],
    1200000,
    "registry promotion",
    ".omo/evidence/attestor-{runId}/G17.json",
  ],
  [
    "G18",
    "P0",
    "workflow assumes direct native Goal state",
    "Goal-disabled runtime fixture",
    "complete lifecycle uses plugin snapshot authority",
    "E-WORKFLOW",
    ["A-LIFE"],
    600000,
    "native Goal mutation",
    ".omo/evidence/replay/{runId}/G18.json",
  ],
  [
    "G19",
    "P1",
    "command alias collision silently misroutes",
    "hostile extension order",
    "registry ownership and collision diagnosis",
    "E-ACT",
    ["A-LIFE"],
    300000,
    "silent alias takeover",
    ".omo/evidence/replay/{runId}/G19.json",
  ],
  [
    "G20",
    "P1",
    "multiple stop handlers make continuation nondeterministic",
    "handler inventory",
    "one coordinator and documented coexistence ordering",
    "E-STATE",
    ["A-LIFE", "A-STATE"],
    300000,
    "duplicate continuation",
    ".omo/evidence/replay/{runId}/G20.json",
  ],
  [
    "G21",
    "P1",
    "async-disabled fallback claims concurrent team",
    "disabled job manager fixture",
    "explicit blocker with no roster success state",
    "E-TEAM",
    ["A-LIFE"],
    300000,
    "false team launch",
    ".omo/evidence/replay/{runId}/G21.json",
  ],
  [
    "G22",
    "P1",
    "mutable plan hash rejects progress or trusts replacement",
    "plan edit corpus",
    "checkbox edit accepted and task replacement blocked",
    "E-STATE",
    ["A-STATE"],
    120000,
    "unreconciled replacement",
    ".omo/evidence/replay/{runId}/G22.json",
  ],
  [
    "G23",
    "P1",
    "in-memory cap is claimed durable on restart",
    "restart schedule",
    "outer and persisted counters have separate oracles",
    "E-STATE",
    ["A-LIFE", "A-STATE"],
    300000,
    "false durable bound",
    ".omo/evidence/replay/{runId}/G23.json",
  ],
  [
    "G24",
    "P1",
    "cleanup or lcx mutates unowned resources",
    "foreign sentinel tree",
    "refusal and dry-run preserve external sentinels",
    "E-WORKFLOW",
    ["A-SEC"],
    600000,
    "unowned side effect",
    ".omo/evidence/replay/{runId}/G24.json",
  ],
  [
    "G25",
    "P1",
    "package provenance is ambiguous or mutable",
    "lockfile and source records",
    "recomputed versions commit and tarball hashes",
    "E-PKG",
    ["A-PKG", "A-REL"],
    900000,
    "mutable provenance",
    ".omo/evidence/release/{runId}/G25.json",
  ],
] as const

export const threatManifest = z
  .object({ schemaVersion: z.literal(1), scenarios: z.array(scenarioSchema).length(25).readonly() })
  .parse({
    schemaVersion: 1,
    scenarios: rows.map(
      ([
        id,
        priority,
        risk,
        immutableInput,
        oracle,
        executor,
        attestors,
        timeoutMs,
        forbiddenSideEffect,
        evidencePath,
      ]) => ({
        id,
        priority,
        risk,
        immutableInput,
        oracle,
        executor,
        attestors,
        timeoutMs,
        forbiddenSideEffects: [forbiddenSideEffect],
        evidencePath,
      }),
    ),
  })
