export const THREAT_ROWS_PRIMARY = [
  [
    "G01",
    "P0",
    "executor fabricates self-consistent green evidence",
    "commit and tarball hashes",
    "verifier-launched OS exits and raw streams",
    "E-ARCH",
    ["A-REL"],
    1200000,
    "executor release verdict",
    ".omo/evidence/attestor-{runId}/G01.json",
  ],
  [
    "G02",
    "P0",
    "malformed state resets bounds or escapes root",
    "fixture bytes and commit",
    "pre/post hashes and unchanged external sentinels",
    "E-STATE",
    ["A-STATE", "A-SEC"],
    120000,
    "state mutation",
    ".omo/evidence/replay/{runId}/G02.json",
  ],
  [
    "G03",
    "P0",
    "repeated turn zero suppresses natural stops",
    "two durable leaf ids",
    "distinct leaves continue and replay is idempotent",
    "E-STATE",
    ["A-LIFE"],
    300000,
    "duplicate continuation",
    ".omo/evidence/replay/{runId}/G03.json",
  ],
  [
    "G04",
    "P0",
    "timed-out handler performs a late side effect",
    "delay point and state hash",
    "wait beyond deadline then compare all sentinels",
    "E-STATE",
    ["A-STATE", "A-LIFE"],
    900000,
    "late state or message write",
    ".omo/evidence/replay/{runId}/G04.json",
  ],
  [
    "G05",
    "P0",
    "prompt injection mutates state or exfiltrates",
    "injection corpus",
    "tool denial receipts and unchanged revision",
    "E-ACT",
    ["A-SEC"],
    120000,
    "forbidden tool call",
    ".omo/evidence/replay/{runId}/G05.json",
  ],
  [
    "G06",
    "P0",
    "synthetic prompt recursively activates workflow",
    "scripted provider transcript",
    "activation counter and revision remain one",
    "E-ACT",
    ["A-LIFE"],
    300000,
    "recursive activation",
    ".omo/evidence/replay/{runId}/G06.json",
  ],
  [
    "G07",
    "P0",
    "flat or batch task shape bypasses fanout cap",
    "task shape corpus",
    "dispatcher receipts and durable item count",
    "E-TEAM",
    ["A-SEC", "A-LIFE"],
    300000,
    "excess task launch",
    ".omo/evidence/replay/{runId}/G07.json",
  ],
  [
    "G08",
    "P0",
    "requested name is mistaken for actual agent id",
    "native task result bytes",
    "stored and messaged IDs equal returned runtime IDs",
    "E-TEAM",
    ["A-LIFE"],
    300000,
    "wrong peer message",
    ".omo/evidence/replay/{runId}/G08.json",
  ],
  [
    "G09",
    "P0",
    "unowned cancellation is reported successful",
    "owned and foreign job ids",
    "job status and owner receipts remain accurate",
    "E-TEAM",
    ["A-LIFE"],
    300000,
    "foreign job cancellation",
    ".omo/evidence/replay/{runId}/G09.json",
  ],
  [
    "G10",
    "P0",
    "worker settles with invalid evidence artifact",
    "artifact fixture tree",
    "realpath regular nonempty current artifact check",
    "E-TEAM",
    ["A-SEC"],
    120000,
    "accept invalid receipt",
    ".omo/evidence/replay/{runId}/G10.json",
  ],
  [
    "G11",
    "P0",
    "active lookup selects foreign or duplicate run",
    "active index fixture",
    "typed conflict and unchanged state bytes",
    "E-STATE",
    ["A-STATE"],
    120000,
    "wrong-run commit",
    ".omo/evidence/replay/{runId}/G11.json",
  ],
  [
    "G12",
    "P0",
    "lock age stealing lets stale owner commit",
    "two process schedule",
    "contention has no write and explicit repair audit",
    "E-STATE",
    ["A-STATE"],
    900000,
    "automatic lock steal",
    ".omo/evidence/replay/{runId}/G12.json",
  ],
  [
    "G13",
    "P0",
    "abort is mislabeled paused cancelled or complete",
    "slow stop transcript",
    "active state persists without explicit control command",
    "E-WORKFLOW",
    ["A-LIFE", "A-STATE"],
    300000,
    "workflow status mutation",
    ".omo/evidence/replay/{runId}/G13.json",
  ],
] as const
